# Generated by Django 4.2.7 on 2024-06-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100, verbose_name='IP адрес')),
            ],
            options={
                'verbose_name': 'IP адрес',
                'verbose_name_plural': 'IP адрес',
            },
        ),
    ]
