# Generated by Django 4.2.7 on 2024-06-12 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewcount',
            options={'verbose_name': 'IP адрес пользователя', 'verbose_name_plural': 'IP адреса пользователей'},
        ),
    ]
