# Generated by Django 4.2.7 on 2024-06-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitca', '0002_alter_viewcount_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_house', models.CharField(max_length=100, verbose_name='название проекта дома')),
                ('description', models.TextField(verbose_name='описание проекта дома')),
                ('square', models.FloatField(verbose_name='площадь дома')),
                ('dimensions', models.CharField(max_length=100, verbose_name='габариты дома')),
                ('walls', models.CharField(max_length=100, verbose_name='материал стен дома дома')),
                ('image', models.FileField(upload_to='houses_gallery', verbose_name='картинка дома')),
            ],
            options={
                'verbose_name': 'проект дома',
                'verbose_name_plural': 'проекты домов',
                'ordering': ['square'],
            },
        ),
    ]
