# Generated by Django 4.2.7 on 2024-06-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitca', '0003_houses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='image',
            field=models.FileField(upload_to='houses_gallery/', verbose_name='картинка дома'),
        ),
    ]
