# Generated by Django 4.2.7 on 2024-06-14 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitca', '0004_alter_houses_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='name_house',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='название проекта дома'),
        ),
    ]
